version: "3"
services:
  ultima:
    image: ultima
    volumes:
      - carga_anexos:/opt/gaa/carga/anexo
    ports:
      - "80"
 
  #proxy reverso de baixa latência. Usado em substituição ao nginx
  haproxy:
    image: haproxy:2.3
    restart: on-failure
    volumes:
      - ./src/main/resources/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      #### Para conseguir rodar https, precisei mandar para dentro da VM o certificado do localhost
      - ./src/resources/certificadoDigital/ultima.selfsigned.pem:/etc/ssl/certs/certificado-aplicacao.pem
      - ./src/resources/certificadoDigital/trusted.pem:/etc/ssl/certs/trusted.pem
      - ./src/resources/certificadoDigital/crl.pem:/etc/ssl/certs/CRL/crl.pem
      
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ultima

# Precisa dessa configuração manual de rede para evitar um conflito com endereços de rede local
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
